---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "persist-service"
  namespace: "itdays"
  labels:
    app: "persist"
spec:
  ports:
  - protocol: "TCP"
    port: 3050
    targetPort: 3050
  selector:
    app: "persist"
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: persist
  name: persist
  namespace: itdays  
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: persist
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: persist
    spec:
      containers:
      - env:
        - name: MONGO_ADDR
          valueFrom:
            configMapKeyRef:
              key: MONGO_ADDR
              name: persist-config
        - name: RABBITMQ_ADDR
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_ADDR
              name: persist-config
        image: gcr.io/itdays-201118/microservice-persist:latest
        imagePullPolicy: Always
        name: microservice-persist
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
data:
  MONGO_ADDR: mongodb://mongodb-mongodb-replicaset.itdays:27017
  RABBITMQ_ADDR: amqp://rabbit:<pwd>@rabbitmq-1-rabbitmq-svc.itdays:5672/
kind: ConfigMap
metadata:  
  labels:
    app: persist
  name: persist-config
  namespace: itdays    
